### ISSUE TITLE
Cannot deserialize planet name table

### ISSUE THREAD

**Issue by XenotropicDev** [rsek/dataforged#25]
I think the planet name tables need to follow the same format as the other table entries at the same level to properly deserialize.

Current: 
![image](https://user-images.githubusercontent.com/6792312/119298020-00463880-bc11-11eb-84d8-8e0b2c96b635.png)
Possible solution: 
![image](https://user-images.githubusercontent.com/6792312/119297973-e3aa0080-bc10-11eb-8b81-b8283db9c326.png)

**Comment by rsek** [comment]
per discord conversation:

<img width="1125" alt="Screen Shot 2021-05-23 at 10 27 49 PM" src="https://user-images.githubusercontent.com/5354757/119300745-228e8500-bc16-11eb-9532-6585ee063b68.png">

reverting to "Sample Names", if only so it's more self-evident why they're like that
