### ISSUE TITLE
Markdown links in moves.json and assets.json have inconsistent formats

### ISSUE THREAD

**Issue by weavejester** [rsek/dataforged#30]
In `moves.json`, markdown links use dashes to separate words, e.g. `#Secure-an-Advantage`, while in `assets.json`, links use underscores, e.g. `#Secure_an_Advantage`. Is it possible to normalize these to use either underscores or dashes?

(I can submit a PR, but I'm not sure which format you'd prefer.)

**Comment by rsek** [comment]
ah whoops, thanks for the catch. luckily it's easy to fix - those were already fixed in my YAML master files for the latest content update, i just forgot to actually push the json output, ha.
