### ISSUE TITLE
moves stat is both a string and an object

### ISSUE THREAD

**Issue by XenotropicDev** [rsek/dataforged#31]
It's really hard to deserilalize the moves.json right now with out adding a custom deserialization rule for typed languages due to the Highest Of type stats using the same keyword "Stat" as the other stats. Consider changing it to be a separate property, adding a move type, or making all the stat fields arrays.

Another option would be to make the trigger "Highest of" for those fields so it follows the same layout as the rest of the moves.

**Comment by rsek** [comment]
yeah, fair enough. i need to give the stat-related keys another pass for that but hadn't gotten around to it yet. in the interest of decluttering the JSON of incomplete content, i've commented the lines containing those keys out of the YAML master files for the time being. i'll leave this issue open until i have a chance to get to it.

**Comment by rsek** [comment]
this should be consistent across moves and assets now. structure goes something like this:

```
"Triggers": [
  { "Text": "Trigger description goes here",
  "Stat Options": {
    "Stats": [ "Iron", "Shadow", "Health" ],
     "Method": "lowest"
    }
  }
]

```
many moves have only one item in the Stats array per trigger.
moves with multiple distinct subtriggers (e.g. Face Danger) have multiple items in the Trigger array
