### ISSUE TITLE
Duplicate ID in reveal a danger alt trigger

### ISSUE THREAD

**Issue by XenotropicDev** [rsek/dataforged#68]
The trigger id for `Ironsworn/Moves/Delve/Reveal_a_Danger/Trigger` is duplicated in two places. It probably should be something like `Ironsworn/Moves/Delve/Reveal_a_Danger_alt/Trigger` for the alternate version.

**Comment by rsek** [comment]
thanks for the catch. should be fixed in 9321fe3
