### ISSUE TITLE
Non unique JSON ids

### ISSUE THREAD

**Issue by XenotropicDev** [rsek/dataforged#72]
The following $id fields are not unique in the 1.3.1 Json files.

Assets:
Starforged/Moves/Assets/Path/Looper/Abilities/2/Loop_Back/Trigger/Options/1/Custom_stat/Time_gap

Moves:
Starforged/Moves/Connection/Develop_Your_Relationship/Trigger/Options/1/Custom_stat/Challenge_Rank

**Comment by rsek** [comment]
huh, good catch. evidently something weird is happening when IDs for custom stats specifically are built, 'cause those are the only two. i'll take a look :)

**Comment by rsek** [comment]
should be resolved in 1.3.2
