### ISSUE TITLE
Grappler  first 'Enabled' ability should be true

### ISSUE THREAD

**Issue by offray** [rsek/dataforged#73]
Hi and again, thanks for Dataforged.

While updating [Rolo Ludo](https://code.tupale.co/Offray/RoloLudo) to support the last data scheme and update our local Starforged TiddlyWiki, I found that the Abilities of the Grappler asset are all false, while the first one should be true.

**Comment by rsek** [comment]
thanks for catching the error. i've fixed it in the 1.4.2 release.

BTW, would you like me to add Rolo Ludo to the projects list in the readme?

**Comment by offray** [comment]
Thanks for your quick fix and for the gift of a morning smile knowing that Rolo Ludo will be linked in the readme. Please add it. BTW, I have more detailed links to Dataforged in our wiki and I will be adding them to the Readme once I have finished some details and house keeping over here.

**Comment by offray** [comment]
I have updated the Rolo Ludo readme to put the English translation of the Dataforged and Datasworn credits that were originally long time ago in the Spanish wiki.

Ps: Should this be a new issue regarding new projects using Dataforged or is fine to continue the talk in a closed issue that started the conversation?

**Comment by rsek** [comment]
> Ps: Should this be a new issue regarding new projects using Dataforged or is fine to continue the talk in a closed issue that started the conversation?

should be updated now (sorry about the delay 😅 ). feel free to open a PR if you'd like any changes made to the description
